### ISSUE TITLE
Austin Lasseter - Resume

### ISSUE THREAD

**Issue by austinlasseter** [ga-students/d.c.-outcomes-homework#1]
[Here is a link to my updated resume on Google docs.](https://docs.google.com/document/d/1AKenMWYORVPk6WQNoOjbLDKdLWfbYY9a7Kzqxc6tZ8Y/edit?usp=sharing)

**Comment by allysonaustin** [comment]
Hi Austin, 

Thanks for submitting your resume! I have few edits and comments for you below. Feel free to reach out with any questions about my comments.

1. Move your contact information above your brand statement as part of your header. I understand that you've only recently had your branding workshop, so your eventual final brand statement will go just beneath your header.

2. I'm going to discourage you from using so many links. From a reader's perspective, it's distracting and unpleasant to read, and, should someone print your resume, they're entirely unusable. Some links are understandable, but it's a bit much right now. Instead, replace the top section with a list of your technical skills and a link to your main portfolio. If you have room later, you can add in some of the other information.

3. Strengthen your data science experience by including your DSI projects. List them, and more importantly include the skills & technologies you employed in created each one. Obviously, this section will continue to grow as you complete the course.

4. List DSI as a single-line item in your education section.

5. Your experience sections are quite brief. Consider including fewer experiences, and instead really beefing up the ones you've included. Give specific examples and details about your experiences by focusing on what you’ve accomplished. You’re definitely on the right track - just push further to make it a stronger representation of your work.

Great work! Let me know if you have questions.
A

**Comment by CoachJoyhaugen** [comment]
Hi Austin, 

You can simply resubmit in this same issue. 

I think you can move your Portfolio Links to your actual Portfolio which will give you more space on your resume to flush out your experiences. 

You can also take out your Doctoral Candidate, University of Maryland (August 2012-May 2013)
as that is technically a part of your education. 

Think with some slight formatting tweaks you can keep your experience on there. But as Allyson mentioned, you will want to beef up your DSI experience as you go. 

Let us know if you have any questions. 

Thanks! 
Joy

**Comment by austinlasseter** [comment]
I've made these changes; the resume is updated. Thanks, A.
