### ISSUE TITLE
Raj Chakrabarty - draft Resume 

### ISSUE THREAD

**Issue by rajachak** [ga-students/d.c.-outcomes-homework#10]
[Raj_Chakrabarty_Resume_2018.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1707036/Raj_Chakrabarty_Resume_2018.docx)

**Comment by allysonaustin** [comment]
Hi Raj,

Thanks for submitting your resume! I have a few edits and suggestions for you below. Feel free to respond with any questions about my comments.

1. Be sure to include your contact information (email/phone) and a link to your portfolio in your header near your name. Replace your professional summary with your completed brand statement.

2. Strengthen your data science experience by building out your DSI section more fully. Include your projects and list the skills you employed to create each one. Also, your resume says that your started the course in Jan 2017 - fix this error.

3. Many of your entries are very lengthy. Be aware that the standard is one page for 10 years of experience; I encourage you to edit down to meet that standard. Generally, 4 bullet points is the sweet spot where you have enough space to give details but not enough to get bogged down. 

4. You have a few typos - run a quick spellcheck to catch them.

5. Some of your spacing/alignment is off, and some of your bullet points are missing periods at the end. Keep the formatting consistent to support readability and avoid unnecessary distraction.

Great work! Let me know if you have questions.
A
