### ISSUE TITLE
Sung, Joshua - Deloitte Resume

### ISSUE THREAD

**Issue by joshsungasong** [ga-students/d.c.-outcomes-homework#18]
Final Brand Statement: 
![image](https://user-images.githubusercontent.com/35347672/36394468-6877e87e-1582-11e8-9823-52dff5059764.png)

[Joshua Sung's DSI Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1742768/Joshua.Sung.s.DSI.Resume.docx)

**Comment by CoachJoyhaugen** [comment]
Thanks!
