### ISSUE TITLE
Joshua Sung - Draft Resume

### ISSUE THREAD

**Issue by joshsungasong** [ga-students/d.c.-outcomes-homework#2]
Here is my draft resume: https://docs.google.com/document/d/1D3laoExvpzTnofkdBqp4moozVQx_FECjCdkhHOl4MwA/edit?usp=sharing

**Comment by allysonaustin** [comment]
Hi Joshua,

Thanks for submitting your resume! Please refer to my comments from our conversation last week. If you have additional questions, please don’t hesitate to reach out. Feel free to submit an updated version, and I’ll happy to take another look.

A
