### ISSUE TITLE
Deloitte Resume - Zaheer

### ISSUE THREAD

**Issue by zrangwala1981** [ga-students/d.c.-outcomes-homework#27]
[Deloitte Resume - Zaheer.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1744561/Deloitte.Resume.-.Zaheer.docx)

**Comment by CoachJoyhaugen** [comment]
Let me know when you resubmit.  Thanks!

**Comment by zrangwala1981** [comment]
Resubmitted!


Zaheer Rangwala
tifosia@me.com
240-938-1385
