### ISSUE TITLE
Puneet Kollipara: Deloitte Resume (Draft)

### ISSUE THREAD

**Issue by kollthing** [ga-students/d.c.-outcomes-homework#30]
[Puneet Kollipara - Deloitte Resume (Draft).pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1749514/Puneet.Kollipara.-.Deloitte.Resume.Draft.pdf)

**Comment by CoachJoyhaugen** [comment]
Let me know once you have resubmitted.
