### ISSUE TITLE
Marker, Christopher - Deloitte Resume

### ISSUE THREAD

**Issue by chriscdm** [ga-students/d.c.-outcomes-homework#34]
[Christopher Marker Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1749819/Christopher.Marker.Resume.docx)

**Comment by chriscdm** [comment]
[Christopher Marker Resume.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1750195/Christopher.Marker.Resume.pdf)

**Comment by CoachJoyhaugen** [comment]
Thanks!
