### ISSUE TITLE
Outcomes Draft Resume v1.0.0

### ISSUE THREAD

**Issue by HIanMartinez** [ga-students/d.c.-outcomes-homework#4]
[Martinez__Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1696927/Martinez__Resume.docx)

**Comment by allysonaustin** [comment]
Hi Hector,

Thanks for submitting your resume! Please refer to my comments from our conversation last week. If you have additional questions, please don’t hesitate to reach out. Feel free to submit an updated version, and I’ll happy to take another look.

A
