### ISSUE TITLE
Puneet Kollipara: Final Resume

### ISSUE THREAD

**Issue by kolliparap** [ga-students/d.c.-outcomes-homework#43]
[Puneet Kollipara - Resume.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1783067/Puneet.Kollipara.-.Resume.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few follow-up comments for you below.

Include your projects in your description for DSI. You’ve branded yourself as a data scientist - this is your opportunity to prove it!
You may find that you run into concerns about space. Should this be the case, consider omitting awards. Some of them are from quite some time ago and could be put into your experience sections, or omitted entirely.
List DSI in your education as a single-line item only.

Let me know if you have questions.
A
