### ISSUE TITLE
Mario Arthur-Bentil - Final Resume

### ISSUE THREAD

**Issue by rioarthur** [ga-students/d.c.-outcomes-homework#45]
[Mario Arthur-Bentil_Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1829804/Mario.Arthur-Bentil_Resume.docx)

**Comment by allysonaustin** [comment]
Thanks for resubmitting! You've done a great job with these edits.

My only recommendation is, once it's in a presentable state, add a link to your website/portfolio so that employers can see examples of your work!

Let me know if you have questions.
A
