### ISSUE TITLE
Michael Schillawski Final Outcomes Materials

### ISSUE THREAD

**Issue by mjschillawski** [ga-students/d.c.-outcomes-homework#48]
Final Resume: https://drive.google.com/open?id=1EBJ9tbrAIJG5nV3Im8LP3xwvw0gp2n4T

Final Cover Letter: https://drive.google.com/open?id=141snaAP3_BsYDUdn6zNf48XxTISMw3wH

Final LinkedIn: https://www.linkedin.com/in/mjschillawski 

Final GA Profile: https://profiles.generalassemb.ly/profiles/mjschillawski

Link to your Blog: https://medium.com/@mjschillawski and/or https://www.mjschillawski.com/words

Link to your Portfolio: https://www.mjschillawski.com and/or https://github.com/mjschillawski

What types of roles/organizations are you interested in: n/a

Top 3 Networking events you have attended: Tech and Food: Union Kitchen; Talk Data To Me: Deloitte Data Community; Talk Data To Me: The Lab DC

What are your top 3-5 technical skills: Python, SQL, Machine Learning, Amazon Web Services.

When we recommend you to organizations, we like to include 2 sentences about you. How would you like us to pitch you? (Write 2 sentences in the third person): n/a

What locations beyond your local market are you job searching in, if you plan to search elsewhere? n/a

Anything you want us to know about your situation or job search in general? I accepted an offer from Deloitte's Federal Analytics and Information Management practice.

**Comment by allysonaustin** [comment]
Thanks for submitting! Excellent work!
