### ISSUE TITLE
Kenneth Yale: FINAL OUTCOMES Materials

### ISSUE THREAD

**Issue by kpyale** [ga-students/d.c.-outcomes-homework#49]
- Final Resume: https://drive.google.com/file/d/1ws8SzUHSTjtDJaazirzY7naNni2oAde-/view?usp=sharing

- Final Cover Letter: N/A

- Final LinkedIn: https://www.linkedin.com/in/kenneth-yale-0088a514/
 
- Final GA Profile: profiles.generalassemb.ly/ken-yale
 
- Link to your Blog: https://medium.com/@kpyale
 
- Link to your Portfolio: https://github.com/kpyale

- What types of roles/organizations are you interested in: program director, strategist, enterprise architect

- Top 3 Networking events you have attended: DCBAI, Houwzer, GA veteran events 

- What are your top 3-5 technical skills: Python, Folium, AWS

- When we recommend you to organizations, we like to include 2 sentences about you. How would you like us to pitch you? (Write 2 sentences in the third person): He is an expert in getting things done in the government and starting businesses

- What locations beyond your local market are you job searching in, if you plan to search elsewhere? Not searching in other markets but not against relocating either

- Anything you want us to know about your situation or job search in general? I am not specifically looking for a job. I will work on my real estate venture and if day-to-day operations get slow I will go back to my position with the Air Force or join the company Decision Lens. I am also looking in the future at a position with AWS, especially if they are awarded the DoDs primary cloud-based contract as the demand for talent will likely increase dramatically.

**Comment by allysonaustin** [comment]
Thanks for submitting!

Resume:
- Your last bullet point in the skills section goes on to two lines unnecessarily. 
- In your DSI section, be sure to list yourself as a Data Science Immersive Student.
- Your resume is quite lengthy, and it can be very overwhelming for the reader. The standard is one page for every 10 years of experience, and I encourage you to pare down to that standard. This will help you focus your efforts on the most relevant and compelling portions of your resume and to omit the rest. Be thoughtful about which bullet or entries may be distracting or less relevant.

Cover Letter: Be sure to submit a link!

LinkedIn:
- List yourself as a Data Scientist in your tagline and include your brand statement in your summary.

These updates need to be made and resubmitted by 9am on Thursday. Let me know if you have questions.
A
