### ISSUE TITLE
Michael Schillawski - Draft Resume

### ISSUE THREAD

**Issue by mjschillawski** [ga-students/d.c.-outcomes-homework#5]
[20180201_Schillawski_Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1697194/20180201_Schillawski_Resume.docx)

**Comment by allysonaustin** [comment]
Hi Michael,

Thanks for submitting your resume! I have few comments for you below. Let me know if you have any questions about my comments.

1. You've already started to push the boundaries in terms of space, and this problem will only persist as you add DSI projects. To combat this consider, paring down the content in your experience entries to avoid anything extraneous (maintained relationships, developed advice) and keep those compelling relevant details (conducted analysis, create visualizations). Your content is  quite strong, and you've used very thoughtful, active language. Keep that up - it reads very well. 

2. Add "and" before the word "convey" in your second bullet under DSI.

3. I understand that you had not completed your branding workshop with this draft, so I anticipate you'll have some changes to your brand statement. Once it's updated, be sure to update it here - and remember a period at the end.

Excellent work! Let me know if you have questions.
A
