### ISSUE TITLE
Final Outcomes Material - Joshua Sung

### ISSUE THREAD

**Issue by joshsungasong** [ga-students/d.c.-outcomes-homework#50]
Final Cover Letter: 
[Data Scientist Cover Letter Template.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1890991/Data.Scientist.Cover.Letter.Template.docx)

Final Resume:
[Joshua Sung's Online Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1891424/Joshua.Sung.s.Online.Resume.docx)

Final LinkedIn: https://www.linkedin.com/in/joshua-sung

Final GA Profile: https://profiles.generalassemb.ly/joshua-sung

Link to your Blog: https://medium.com/@joshsungasong

Link to your Portfolio: https://joshuasung.me/

My Github: https://github.com/joshsungasong

What types of roles/organizations are you interested in:
I am open to any Data Scientist position, especially positions that will challenge me to build my data science skills, especially skills I need to hone in on. I expect to work in an organization that would give me a decent work/life balance. If I were to list any organizations that I am eyeing on, they would include Booz Allen Hamilton, Deloitte, The Washington Post, ICF International, US Census Bureau, Federal government, etc.

Top 3 Networking events you have attended:
- Data Processing for Machine Learning / AI / Natural Language Processing
- Exploring DC data using Spatio-Temporal Visualization
- Deloitte Hackathon
- Talk Data to Me (Deloitte Insight Studio)
- Talk Data to Me (The Lab DC)

What are your top 3-5 technical skills:
- Python (Sci-kit learn, Pandas, NumPy)
- Machine Learning
- SQL

When we recommend you to organizations, we like to include 2 sentences about you. How would you like us to pitch you? (Write 2 sentences in the third person):

Josh is a data scientist that aims to solve complex problems by breaking them down into simple business solutions. Josh is a curious data scientist who is willing to learn as much as he can in the field to become an effective and knowledgeable data scientist. 

What locations beyond your local market are you job searching for, if you plan to search elsewhere?

I would like to preferably  stay in the Washington, D.C. area but willing to relocate.
Locations include: New York, NY; Chicago, IL, Seattle, WA; Boston, MA; Austin, TX; Houston, TX; Philadelphia, PA

Anything you want us to know about your situation or job search in general?

Just want to decompress, reflect and process on what I've learned at DSI so far and definitely want to get started on job searching after applying for a few positions so far.

**Comment by allysonaustin** [comment]
Thanks for submitting! Excellent work!

A
