### ISSUE TITLE
Hector Ian Martinez - Final Outcomes Material

### ISSUE THREAD

**Issue by HIanMartinez** [ga-students/d.c.-outcomes-homework#51]
Final Resume: [HIMartinez_resume_for_submit.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1891855/HIMartinez_resume_for_submit.pdf)
Final Cover Letter: [CL.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1891859/CL.pdf) 
Final LinkedIn: https://www.linkedin.com/in/hector-ian-martinez/
Final GA Profile: https://profiles.generalassemb.ly/profiles/himartinez
Link to your Blog: https://medium.com/@hi.martinez (posts to be completed)
Link to your Portfolio: https://www.himartinez.com/

What types of roles/organizations are you interested in: 

A: I am pretty open to any data scientist position at the moment. I’d like to explore my options but would like a place where I can hone the skills I’ve learned and learn new skills continually. It is important to me that I be able to have a decent work/life balance and would steer away from work cultures that expect you to give all of your time to the job.

Top 3 Networking events you have attended: 

* Talk Data to Me (Mapbox)
* Deloitte Hackathon
* Talk Data to Me (The Lab DC)

What are your top 3-5 technical skills: 

* Python  
* Web Scraping 
* Neural Networks

When we recommend you to organizations, we like to include 2 sentences about you. How would you like us to pitch you? (Write 2 sentences in the third person): 

*A:* Hector’s strengths lie in his perseverance to solve problems that present themselves. Additionally, more than just working with the data, he knows how to get people engaged in the story that the data tells.

What locations beyond your local market are you job searching in, if you plan to search elsewhere? 

*A:* I am planning on staying in DC

Anything you want us to know about your situation or job search in general? 

*A:* I am willing to take a bit longer to find a workplace that will be the right fit for me culturally.

**Comment by allysonaustin** [comment]
Thanks for submitting! Excellent work!

A
