### ISSUE TITLE
Chris Marker's Final Outcomes Materials

### ISSUE THREAD

**Issue by chriscdm** [ga-students/d.c.-outcomes-homework#52]
Final Resume: 
![image](https://user-images.githubusercontent.com/35273594/38524958-7ab63910-3c1e-11e8-8dc2-a3d0349cfc41.png)

Final Cover Letter: 
![image](https://user-images.githubusercontent.com/35273594/38524969-87373022-3c1e-11e8-82b0-e917b0764a6d.png)

Final LinkedIn: 
https://www.linkedin.com/in/christopher-marker-42961b33/
 
Final GA Profile:
https://profiles.generalassemb.ly/christopher-marker 

Link to your Blog:
https://medium.com/@chris.d.marker (posts written but pending)

Link to your Portfolio:
https://github.com/chriscdm (incomplete)

What types of roles/organizations are you interested in: Environmental non-profits, startups, consulting

Top Networking event you have attended: Deloitte Hackathon, GA First Fridays

What are your top 3-5 technical skills: Python, SKLearn, Pandas

When we recommend you to organizations, we like to include 2 sentences about you. How would you like us to pitch you? (Write 2 sentences in the third person): I am a hardworking, dynamic individual that is willing/able to learn new things quickly and will do what it takes to get the job done.  

What locations beyond your local market are you job searching in, if you plan to search elsewhere? Seattle, New York

Anything you want us to know about your situation or job search in general? I need a paycheck!!!

**Comment by allysonaustin** [comment]
Thanks for submitting! I've listed a few tweaks and edits below. 

Resume:
- Be sure you list yourself as a Data Science Immersive STUDENT

Cover Letter:
- Be specific in your cover letter. You refer to the "work" that GA does; be explicit about what that work is. You mention that you've gained necessary skills - such as? Don't make the employer draw the conclusions with little to no context.

LinkedIn:
- Copy + paste your descriptions from your resume into your LinkedIn experience.
- Add your brand statement to your summary on your profile.

These updates need to be due by Thursday at 9am. Let me know if you have questions.
A

**Comment by chriscdm** [comment]
[Cover Letter Sample (1).pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1913741/Cover.Letter.Sample.1.pdf)

https://www.linkedin.com/in/christopher-marker-42961b33/

Hey Allyson, I have made the requested changes on my cover letter and LinkedIn. 

On the resume, where did you want me to put that I'm a Data Science Immersive Student?
