### ISSUE TITLE
Sian Lewis Outcome materials

### ISSUE THREAD

**Issue by allsian** [ga-students/d.c.-outcomes-homework#53]
Résumé: 
[Sian_Lewis_Data_Scientist.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1892021/Sian_Lewis_Data_Scientist.pdf)

Cover Letter: 
[Sian Lewis - GA-Cover-Letter.pdf](https://github.com/ga-students/d.c.-outcomes-homework/files/1900980/Sian.Lewis.-.GA-Cover-Letter.pdf)

LinkedIn: https://www.linkedin.com/in/allsian/
GA Profile: https://profiles.generalassemb.ly/profiles/sianlewis
Blog: https://www.sianlewis.org/blog#blog
Portfolio: www.sianlewis.org / www.github.com/sianlewis

What types of roles/organizations are you interested in: I am interested in leadership or managerial roles, or roles where I interface with clients. I am naturally inclined to work in formal, established organizations that value diversity.  

Top 3 Networking events you have attended:

Talk Data to Me - Mapbox
Big Data Meetup
Talk Data to Me - Deloitte 
Data Wranglers

What are your top 3-5 technical skills:
Data Cleaning & Wrangling
Metadata Management (Big Data)
Python
Machine Learning
Client Engagement

When we recommend you to organizations, we like to include 2 sentences about you. How would you like us to pitch you? (Write 2 sentences in the third person):

Sian is a people-focused data scientist who delivers value by helping clients cut through clutter. She is a natural leader who committed to predictive analytics and personal growth. 

What locations beyond your local market are you job searching in, if you plan to search elsewhere?
DC, Miami or New York. DC is the priority. 

Anything you want us to know about your situation or job search in general?
I need a job as soon as humanly possible - one that does not include extensive travel.

**Comment by allysonaustin** [comment]
Thanks for submitting! Great work!

Cover letter: this link is to your resume; can you submit your cover letter?

**Comment by allsian** [comment]
@allysonaustin I accidentally put in the wrong file. I've corrected the link.
