### ISSUE TITLE
Mario Arthur-Bentil - Final Materials 

### ISSUE THREAD

**Issue by rioarthur** [ga-students/d.c.-outcomes-homework#54]
Final Resume: [Mario Arthur-Bentil_Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1891918/Mario.Arthur-Bentil_Resume.docx)
Final Cover Letter: 
[Mario Arthur-Bentil_Cover Letter.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1903196/Mario.Arthur-Bentil_Cover.Letter.docx)
 Final LinkedIn: https://www.linkedin.com/in/marioarthurbentil/ 
Final GA Profile: profiles.generalassemb.ly/marioarthurbentil 
Link to your Blog: https://medium.com/@m.arthurbentil 
Link to your Portfolio: https://github.com/rioarthur
What types of roles/organizations are you interested in: Data scientist positions in larger retail organizations, design firms, marketing
Top 3 Networking events you have attended:  Deloitte Hackathon, 1776 The Challenge Cup Global Finals, GA First Fridays
What are your top 3-5 technical skills: Python, Tableau, Machine Learning, Data Visualization
When we recommend you to organizations, we like to include 2 sentences about you. How would you like us to pitch you? (Write 2 sentences in the third person): Mario has over 6 years of experience in data visualization, strategy, and consulting. With his machine learning knowledge, Mario can bridge the gap between those not in the data science community and those who are.
What locations beyond your local market are you job searching in, if you plan to search elsewhere? DC, Austin, San Diego, Dallas, Los Angeles
Anything you want us to know about your situation or job search in general? I'm willing to go a month or two without a job, but I'm still aggressively looking for a new job.

**Comment by allysonaustin** [comment]
Thanks for submitting! Excellent work.

Can you please include a link to your cover letter?

A
