### ISSUE TITLE
Mario Arthur-Bentil: Resume

### ISSUE THREAD

**Issue by rioarthur** [ga-students/d.c.-outcomes-homework#6]
[Mario Arthur-Bentil_Resume.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1697196/Mario.Arthur-Bentil_Resume.docx)

**Comment by allysonaustin** [comment]
Hi Mario,

Thanks for submitting your resume! I have few comments for you below. Let me know if you have any questions about my comments.

1. Add a link to your portfolio in your header, and replace your executive summary with your brand statement.

2. Your technical skills section looks very sparse. Include as many hard skills as possible and don't be hesitant to enumerate specifics. You may not need to break them up into these categories; be thoughtful about this.

3. As you complete the course, add your projects to the DSI section. Focus on describing the project through the skills you employed to create each one.

4. A couple of quick stylistic notes: 
- Delete the space between your roles at E&Y and the Federal Reserve Board - the current layout at first seemed like you had forgotten to include the company name.
- Put spaces on either side of the dashes in your dates (January 2018 - August 2018).

Great work! Let me know if you have questions.
A

**Comment by rioarthur** [comment]
Hi Allyson,

My apologies for the late response. Thank you for the feedback!

Regards,

Mario
