### ISSUE TITLE
Kenneth Yale Master Resume

### ISSUE THREAD

**Issue by kpyale** [ga-students/d.c.-outcomes-homework#9]
[Master Resume Feb 2018.docx](https://github.com/ga-students/d.c.-outcomes-homework/files/1699891/Master.Resume.Feb.2018.docx)

**Comment by allysonaustin** [comment]
Hi Kenneth,

Thanks for submitting your resume! I have a few edits and suggestions for you below. Feel free to respond with any questions about my comments.

1. Omit your specific address from the header; city/state is sufficient. 

2. Your resume needs to be updated to reflect your current experience and skills. Replace your profile and first skills section with your brand statement and a section with your technical skills. Add DSI to the top of your experience section and include a description of the course, and specifically list the projects as you complete them. Be sure to emphasize the skills you used to create each one. 

3. Your resume is quite lengthy, and it can be very overwhelming for the reader. The standard is one page for every 10 years of experience, and I encourage you to pare down to that standard. This will help you focus your efforts on the most relevant and compelling portions of your resume and to omit the rest. Be thoughtful about which bullet or entries may be distracting or less relevant. You've done a fabulous job of giving specific details and accomplishments - apply this same focus to your DSI section

4. Some of your bullet points have periods at the end and some do not. Keep your formatting consistent. 

Great work! Let me know if you have questions.
A
